### ISSUE TITLE
A critique of the algorithm

### ISSUE THREAD

**Issue by DonaldTsang** [elitexvzf/Textpx#1]
As https://old.reddit.com/r/Python/comments/chiead/i_recently_made_a_zliblike_program_that_can_be/ have stated, PNG uses zlib compression, thus all it did is combine images with a stream of copressed data. This is really steganography (hiding data in plain sight) and not compression.

**Comment by elitexvzf** [comment]
Noted, sorry I'm new to compressions and imaging things.
